apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce-dev
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8400
      targetPort: 8400
  type: ClusterIP